### ISSUE TITLE
Flexible content

### ISSUE THREAD

**Issue by kokers** [Hube2/acf-reusable-field-group-field#12]
Does this work with flexible content? I can't make this work. The fields from the Reusable field group are visible when field is added in the other field group or in repeater, but it's not present when used in flexible content (if in flexible content there is a repeater, theres no fields also). 

EDIT ---

I did some digging, and it looks like it's not working if there is only repeater. I was playing around and didn't notice this earlier. When I add Reusable field inside repeater, it doesnt show up on page. But if I add this field inside repeater AND add a standalone reusable field with the same group that is in repeater, fields from that group are visible in the repeater. So this works: http://prntscr.com/9fbj18 this does not: http://prntscr.com/9fbjak Same goes for flexible content. So the issue isn;t that it doesnt work in flexible content, but it simply doesn't work if it's in repeater or flexible content (unless you add top level reusable field, but there is no point of doing that).

Not fully sure how the code works, but I think function scan_group_fields might be a reason for that, as it looks like it will be looking for reusable fields in children if there is any in the first level of fields ( if that make sense ;o))

Also on a side note, I doubt that's an issue, but in source code there is "acf_resulable" instead of "acf_reusable" (a typo) in all "wp_cache_get" calls. It's all consistent, so that's not a problem, but at first it looked like that a bit ;o) I don't know if that was intentional or not, just wanted to let you know.

**Comment by Hube2** [comment]
Thanks for letting me know about this, I'll take a look at it. It's funny because I've been testing with field groups added at both the top level and at various levels in repeaters and flex fields to make sure that it was working in all of them so I may not tested in just a repeater of flex field.

Yes, it's a typo, but I'll probably fix it. If I create a typo once my editor auto completes variable names, great for making sure I use the same name but that also means it's always a typo. It should be cleaned up.

**Comment by kokers** [comment]
Thanks for quick response. For now I'm cheating and adding group I use in my flexible layouts also as a top level field and it works fine. If you need anymore details just let me know. Thanks again :o)

**Comment by Hube2** [comment]
The newest commit should fix this. You were absolutely correct, it was not scanning repeaters and flex fields unless there was already a reusable field and this is now corrected to scan sub fields on every field.

This probably also corrects previous issues dealing with the same thing, but your bug report gave me the clue I needed to figure out why this was not working for some people and I was unable to recreate the bug. I really appreciate the details you added.

~JH

**Comment by kokers** [comment]
Awesome. I will test it right away. Thanks!

**Comment by kokers** [comment]
Ok. It seems like it's working fine now :o) Thanks for quick fix. 

I found one more thing. It seems like the scan_group_fields is called on every wordpress page and this is causing a Notice in my debug.log:

18-Dec-2015 20:37:12 UTC] PHP Notice:  Undefined index: type in /Users/kokers/Sites/pixplus_themes/corpo005/wp-content/plugins/acf-reusable-field-group-field-master/acf-reusable-field-group-field-v5.php on line 546

No matter if it's dashboard, media subpages and so on, the function is called everytime. Does this have to be called on each wordpress page?
