### ISSUE TITLE
Cannot create reusable field group

### ISSUE THREAD

**Issue by smarterdigitalltd** [Hube2/acf-reusable-field-group-field#13]
Hi,

Unfortunately getting an error when trying to create the Reusable Field Group:

`Cannot read property 'childNodes' of null`

https://www.evernote.com/l/AOP8obiy1dJA3aJNuABM9o4tx4m20pui6E0

FYI - I downloaded the very latest version, just a few mins ago.

Thanks very much - let me know if I can help troubleshoot further.

**Comment by Hube2** [comment]
This should be corrected. It was due to a PHP warning (with display errors on) that caused the AJAX request to fail. Please test with the newest version and let me know if it's fixed for you or not.

**Comment by smarterdigitalltd** [comment]
Great stuff - that's working. Thanks very much indeed!
