### ISSUE TITLE
Very slow server response time

### ISSUE THREAD

**Issue by Bobolions** [Hube2/acf-reusable-field-group-field#15]
Hi,

I use this plugin because a have a lot of the same field groups. I use ACF as a page builder. This plugin has to load a lot of fields, I understand  that. The only problem is that in the Google page speed test the server response time is 7 seconds! If I disable the plugin, the response time 0.80 seconds. Do you know what can cause this problem?

Hope to hear from you soon and best regards.

**Comment by Hube2** [comment]
I can't really say to be honest. The functions in the plugin only run when acf hooks are called. It also saves the field groups that it creates as local JSON files. The only time the field groups are recreated and a lot of work is done is after you update a field group in ACF. Saving a field group in ACF causes the "cache", if you want to call it that, to be cleared. Is there a significant difference in page load time with this plugin disabled?

**Comment by Bobolions** [comment]
Hi, thanks for the quick reply. This is much appreciated!!
I found the solution. I set my PHP version in the hosting environment to PHP 7.0.2. After that, it worked like charm! Before it was on PHP 5.6. 

Version:
ACF v5.3.3.2
WP v4.4.1

Q1: Do you know why this is?

Q2: Are you planning to maintain this plugin in the future? The answer to this question is super important to me because I am planning to use this plugin for all my clients.

Q3: If for some reason this plugin might not work anymore in the future... can I easily go back to "normal" use of ACF without this plugin without losing all the settings / stored data? Some explanation:

I use ACF now as a page builder. The builder has items like text or image or gallery. All the items are called with your plugin. A user can add for example a row with 3 columns. In every column he or she can add items. If a user would add 3 items to all 3 columns, there are 9 items loaded with this plugin. The items are all identical (except for the field key off course). If this plugin would not work anymore, can I copy all individual fields (that together form an item) to the 3 columns without losing any data or stored fields? I'm looking for a good backup plan :). Any advice welcome!

Q4: The settings of the reusable field are now all set to "Field Key Prefixing" only. Do you think this is the best setting if I ever wanted to disable this plugin, copy all fields manually, and don't lose any data? 

Thank you for your time and building this great plugin!!

**Comment by Hube2** [comment]
1) One of the improvements in PHP 7 is that it's supposed to be faster.

2) Yes, I'm planning to maintain it, unless something significant happens, like ACF not longer exists.

3) As I said above, when this plugin rebuilds the field groups it stores creates a JSON file in a folder in the plugin. If all else fails this JSON file could be imported directly into ACF.

4) Field name prefixing is really only important if duplicated fields will be siblings. For example, if the same field group is reused at the top level of field groups that appear on the same post. Field name prefixing is not as important if the fields are inside of repeaters whose parents have different field names.

Field key prefixing can be removed under some conditions. For example, if you have nested reusable fields. That is, you have a field group that has a reusable field group in it that that reusable field group also contains reusable field groups. More than likely the field key prefixing can be turned off for the nested groups. Although, to be honest I have not tried this.

Overall it is important that field names be unique for any post or term and that field names are always unique when used on options pages. Field keys must be unique site wide.

And, like I said for 3, you should be able to import the field groups created by this plugin directly into ACF.

**Comment by Bobolions** [comment]
Hi,

Thanks for the quick comment! I tested your backup solution and it works perfect! 
Also a thank you for the other advices. 

Five stars for this plugin. Saves me a TON of work.
