### ISSUE TITLE
Iterating efficiently through reusable fields in template

### ISSUE THREAD

**Issue by macolo** [Hube2/acf-reusable-field-group-field#16]
Hi,

First, this is an awesome plugin for ACF, thank you. It works very smoothly and cleanly for the layout / field generation in the backend. 

I would quickly like to share my thoughts and challenges around iterating efficiently through reusable fields.

Let's assume we have this setup:

```
- Field Group: Reusable Fields
  - Field: text_block
  - Field: image_block
  - Field: portrait_container (Flexible Content)
    - Layout: ...
      - Field: ....

- Field Group: Page Content
  - Field: Page Content (Flexible Content)
    - Layout: One Column
      - Field: Content (Reusable Field: Reusable Fields) 
    - Layout: Two Columns
      - Field: Left (Reusable Field: Reusable Fields) 
      - Field: Right (Reusable Field: Reusable Fields) 
```

So, we have our content blocks defined in the `Reusable Fields` Field Group and are using them in two different layouts for the page content.

In the template I would now like to iterate as DRY as possible through the different blocks of a page that have been added by the editor.

Because the field names are different for each Page Content Layout, I would have to repeat the HTML generation for, let's say, `image_block` inside each Page Content Layout.

What is the best way to write DRY templates with Reusable Fields?

The only viable solution I can think of would be using `get_template_part()` and passing in the reusable field name through something like `set_query_var('image_block', $reusable_fields_image_block)` (see https://github.com/roots/sage/issues/1414 in regards to the discussion about passing variables to a partial template.)

**Comment by Hube2** [comment]
How I would do this would greatly depend on the circumstances, but it most cases I probably would create a PHP function, or even a PHP class for more complicated situations. On the other hand it could probably be done with a simple loop under the right conditions.

But in this case, it may not even be necessary to leave the field prefixing in place. Let's say that you have a felxible content field like you say and you reuse field groups inside the layouts of you flex field. The field names have a good chance of already being unique. Take a look at my answer on issue #15 about when field name and field key prefixing is needed.

So lets say that you have a flex field named `flexible_field` and you have a group that use reuse in two different layouts, that actual names of the layouts done matter. Let's just for argument say that you're reusable field only has 1 field in it name `text_field` and you turn of field name prefixing and let's say that you add 3 layouts to the flex field. The field names stored in that database will look like this.
```
flexible_field_0_text_field
flexible_field_1_text_field
flexible_field_2_text_field
```
The field names are already unique enough that field name prefixing is not needed.

I put the warnings in about the prefixing of field names and keys for the 90% of the people that will likely use this plugin without digging into where and when it might be safe to turn it off. Again, like I said in #15, sibling fields need to have unique names and overall the exact field name taking into account what all of the variables already in place in ACF need to be unique on each post.

Hopefully I have not confused this even more for you and I've made it a bit simpler.

**Comment by macolo** [comment]
Thanks @Hube2 , that helped. The DRY can be solved entirely through partial templates. Works like a charm.

There are three types of partials:

- layout partials
- iterators (one for blocks and one for layouts)
- blocks

Example for a layout partial:
```
<div class="row">
    <div class="layout-two-columns">
        <div class="col-md-6">
            <div class="left">
                <?php
                // here we're using name prefixing because there are two fields we need to keep apart.
                if (have_rows('two_columns_left_flexible_content')):
                while (have_rows('two_columns_left_flexible_content')): the_row();
                    get_template_part('subparts/content-blocks-iterator');
                endwhile;
                endif;
                ?>
            </div>
        </div>

        <div class="col-md-6">
            <div class="right">
                <?php
                // here we're using name prefixing because there are two fields we need to keep apart.
                if (have_rows('two_columns_right_flexible_content')):
                    while (have_rows('two_columns_right_flexible_content')): the_row();
                        get_template_part('subparts/content-blocks-iterator');
                    endwhile;
                endif;
                ?>
            </div>
        </div>
    </div>
</div>
```

Example for an iterator partial:
```
<?php
if (get_row_layout() == "one_column_layout"): get_template_part('subparts/layouts/layout-one-column'); endif;
if (get_row_layout() == "two_columns_layout"): get_template_part('subparts/layouts/layout-two-columns'); endif;
if (get_row_layout() == "fluid_layout"): get_template_part('subparts/layouts/layout-fluid'); endif;

```

Example for block partial:

```
<div class="text-box">
    <?php the_sub_field('text'); ?>
</div>
```
