### ISSUE TITLE
Upgrade to ACF 5.3.4 and reusable groups disappeared from UI. 

### ISSUE THREAD

**Issue by chrisgoddard** [Hube2/acf-reusable-field-group-field#18]
Content is still appearing on front end. No PHP or JS errors that I can see. Reusable field just isn't showing up. Any ideas?

**Comment by kokers** [comment]
Hmm, I've got latest ACF version (5.3.4) and I believe latest version of reusable field group (Version 0.1.7).  I see fields from Reusable group in a page edit, as a field type when adding new field group or edditing existing and so on. Don't see any issues after update. Can you add some additional informations?

**Comment by Hube2** [comment]
Thanks kokers for confirming for me, I also did a test and everything seems to be working. More details was what I was going to say.

**Comment by chrisgoddard** [comment]
Sorry! Figured it out. It looks like I had to re-save some of my field groups so that the JSON files were updated.

**Comment by chrisgoddard** [comment]
Ok, sorry I reopened because I ran into it again but I think I got it now.

What seems to be happening is a conflict between the theme /acf-json/ folder and the json file in the plugin. When I resave the field group, it creates a version in /acf-json/ and it's that version that is used (which doesn't include the sub fields) instead of the version in the reusable fields plugin.

At least that's what it appears to be - does that make sense? Would there be a way of making the plugin check for an /acf-json/ folder in the theme and using that if present instead of the plugin folder itself?

**Comment by Hube2** [comment]
Thanks for the additional info, I'll look into it and see what I can find.

**Comment by Hube2** [comment]
I just did another test with local json enabled for the theme and I'm still not seeing any problems. The field group located in the theme acf-json folder should be the field group before it is modified. There must be something else going on. Do you have any other plugins running? Have you tried dactivating them? Is there something in the theme that could be interfering?

**Comment by harbingerlabs** [comment]
Experiencing the same issue. 5.3.3 on one site w/ the same field groups is working fine; 5.3.4 doesn't show up at all - same code base essentially.

I've disabled all plugins but ACF & ACFRFG but no dice. 

Rolled back to 5.3.3 and working again. Maybe that can help pinpoint the issue - This plugin is a lifesaver!

**Comment by Hube2** [comment]
Can someone that is having this problem export the field groups to JSON, compress them to a .zip file and attach them here. I'd like to test out fields that are doing this because I am not able to recreate the issue.

**Comment by harbingerlabs** [comment]
@Hube2 - attached are the field groups that were giving me troubles on 5.3.4. Also tested a brand new install w/ simple reusable field group on 5.3.4 with the same 'no-show' issue occuring.

thank you

[acf-fieldgroups.zip](https://github.com/Hube2/acf-reusable-field-group-field/files/133407/acf-fieldgroups.zip)

**Comment by Hube2** [comment]
Forgive my ignorance, what is RFG?

**Comment by Hube2** [comment]
I have some bad news and I have some good news. First the bad news, I imported your field groups and they appear to be working correctly. The good news is that there have been some other problems related to importing in ACF that are fixed on the Dev version, which is the version that I'm using, and those changes should be in the next update. I don't know when the new version of ACF will be available for you to update.

**Comment by harbingerlabs** [comment]
@Hube2 - RFG = Reusable Field Group :) 

Also, thank you for the update re: ACF. I'll stay on 5.3.3 until the next version drops. 

Thanks again

**Comment by Hube2** [comment]
I guess I am being ignorant, sorry, wasn't even thinking that you were referring to this plugin.

**Comment by Hube2** [comment]
I have just updated the plugin again and added additional acf cache clearing. I've also added a warning/suggestion about not using this plugin on production sites to the readme. I think that this plugin should be used as a development tool because the cache clearing that must be done may have a significant effect on site speed.
