### ISSUE TITLE
Use in Flexible Content Layout only shows a single text box

### ISSUE THREAD

**Issue by Idealien** [Hube2/acf-reusable-field-group-field#19]
Love the concept, but thus far my use case for it (to replace a set of identical fields inside a layout for a flexible content group has not proven to be successful. After creating the separate field group (with ~30 fields) and choosing the reusable type on the main field group, when I go to the custom post type edit window I only see a single text field within the layout.

**Comment by Hube2** [comment]
I just did a quick test and it is working correctly for me. Not sure if it's something else on your site or specific to the groups you've created. If you export the 2 field groups in question and upload them as a .zip file I'll import them into my test site and see what happens.

**Comment by Idealien** [comment]
If it is site related (Multisite, custom wp-content folder) it appears to be affecting my attempts with other acf-reusable-field-group-field repos on github that are forked / variants of yours. 

I was however successful with a different component field plugin. It also separates reusable field groups in the UI - which I think will make managing them much easier to co-ordinate.

**Comment by Hube2** [comment]
Being a multi-site installation could be the problem. I will need to check into this. More than likely it has to do with the way that I'm saving JSON files in sub-folder in the plugin. They are not divided per site and more than likely there is some type of cross site problem caused by this.

**Comment by iambriansreed** [comment]
@Idealien I am having the same issue with a more complicated field group inside a flexible content group. Bug not enhancement BTW.

**Comment by Hube2** [comment]
I could make it so that local JSON is not used on multisite installations for now to see if that solves the problems on multisite, but this would slow down the operation of the plugin and the sites since the field groups would need to be rebuilt on every page load.

**Comment by Hube2** [comment]
This plugin will now store its local JSON files in sub folders on multisite installs.
