### ISSUE TITLE
Unable to use nested sub_fields that are part of a re-usable group?

### ISSUE THREAD

**Issue by BoweFrankema** [Hube2/acf-reusable-field-group-field#24]
Hi John,

Thank you for all your hard work on this extension, it will literally save me hundreds of hours of development work in the long run. I've been playing around with creating re-usable groups and I'm running into an issue. 
#### Flexible Content Field

---- Row (Layout)
                 ------- One Sub Field
                 ------- Two Sub Fields
                 -------- Repeater Sub Field
                 ------------------  **Repeater Sub Fields added by re-usable Field Group**
---- Slider (layout)
---- Grid (layout)

I made a quick little video to show you my setup (if that helps).
http://quick.as/e6b6IBQy4

This might not be a standard setup but everything is working as it should when I'm not using re-usable groups. I can loop through repeater fields that are part of the flexible content layout no problemo. I'm doing this using the get_sub_field function and have_rows function.

What is even weirder is that a relationship field inside a re-usable Group does work and returns the IDs. But when I try to echo a field I got nothing.

Any idea what might be going on?

**Comment by Hube2** [comment]
This is mostly note for myself, I'll do some testing.

Field Group
--- flex field
------ nested repeater field
--------- resusable field group (field name prefixing turned off)

Field group reused above
--- repeater
------ sub field <--- not returning value

**Comment by Hube2** [comment]
I'm not sure what's going on. I did a test and it wasn't working then I tried some things and while I was attempting to debug the problem it suddenly started working again.

Try deleting the reusable field group from the repeater and adding it in again.

**Comment by BoweFrankema** [comment]
The thing that I find weird is that my relationship field IS returning. But the regular fields are not. I'll try recreating the field group as you suggested. Thanks for looking into it so quickly :-)

**Comment by Hube2** [comment]
Basically what I did was, I created a field group with a repeater in it. Then I created a field group with a flex field with a repeater and a reusable group in it to test. 

I was seeing a problem. But the problem wasn't with the reusable group it was with the repeater in the main group. If I used get_sub_field on the first repeater it returned the correct array but have_rows() returned false.

The next thing I did was remove the reusable field to test it that way, and it started working. Then I added the reusable field back in and that was working. I really didn't rebuild anything, I just deleted the field, save the group and then added it again.

Mu suspicion is that it has something to do with caching, but I'm not positive because I have been unable to recreate the problem again.

I did just upload a new update and I'm now clearing the local JSON files when ACF saves an 'acf-field' post type as well as the 'acf-field-group' post type. There's a possibility that AFC did not did not trigger the save_post action on the field group and only triggered it on the field, but that's just a guess at this point.

Let me know if you have more trouble and I'll look at it some more.

**Comment by BoweFrankema** [comment]
Hi John,

Your strategy worked. Basically I got it to work by.

- Duplicating Flexible Content Layout 
- Move all old fields/subfields to this new duplicated layout
- Saving Field Group
- Remove the old layout field and rename the duplicated field to the old one. 

It's certainly a weird issue to have and I'd probably never figured it out myself. Do you think this would be a one time issue or could this happen on installations that import the JSON field groups for the first time?

**Comment by Hube2** [comment]
I'm hoping that this is a one time issue, but if you see other problems let me know

I honestly think is was a caching issue and I think the change I added will solve the problem. When field groups are used the first time this plugin builds local JSON field groups. These field groups are loaded before the field groups in the ACF editor. So, basically, the ones in the ACF editor are not used if they contain a reusable group. When you edit and save a field group in ACF, and this should include importing, that triggers this plugin to delete all of it's local JSON files and rebuild them. I was removing the files when an 'acf-field-group' post was saved but not when and 'acd-field' post was saved. I hope that I have it working 100% now, the only thing I can say is that if there are any more problems to let me know and I'll dig into it some more.

The thing I found really odd what that get_field('flexible_content_field') did return all of the values for all of the nested repeaters while have_rows('first_repeater') returned false. That does not make any sense whatsoever to me. If I could reliably recreate the issue then I could look into some more, as it is I don't really have time at the moment to do testing to figure out how to recreate this.

**Comment by BoweFrankema** [comment]
Hi John,

There is still something weird going on, even with the latest version.. I managed to get one layout block working with the tactic I posted before, but now I'm stuck again trying to get the other layouts to work. LIke you I'm unable to reproduce the failure consistently so I'm sadly not able to give you more info. I'll just keep trying things and see how/why this happens. Thanks again for your time on this, and I'll report back when I found anything new.

**Comment by iambriansreed** [comment]
+1

**Comment by Hube2** [comment]
For anyone that's having this intermittent issue, The same type of thing has been reported on the ACF support forums about the same kind of thing, that is, repeater sub fields nested in a flex field are not returned. I haven't had time to look at that. It is extremely hard to debug something when it cannot be reliably reproduced. If anyone can tell give me a set of steps to follow that will reproduce the bug in ACF, either with or without this plugin active then I can look at it and/or report it to Elliot.
