### ISSUE TITLE
render_field 

### ISSUE THREAD

**Issue by ManAnRuck** [Hube2/acf-reusable-field-group-field#28]
render_field is comment out, so when I want to include the acf php export file, there are no fields to edit. :(

**Comment by ReggaePanda** [comment]
when i add following to acf-reusable-filed-group-field-v5.php after opening the build_field_gorups function, i see my fields after including the acf php file

`
		function build_field_groups() {
			$acfFieldGroups = acf_get_local_field_groups();
			if(!empty($acfFieldGroups) && $acfFieldGroups[0]['local'] == 'php') {
				$this->local_loaded = false;
			}
`

do you know a better way?

**Comment by Hube2** [comment]
I not sure I completely understand what you mean? Do you want to export field groups using ACF that include reusable fields? 

The fields that this plugin adds to field groups is not exported with the field groups on purpose. This also means that these fields will not be included in the PHP export. I'm not going to change this.

Ff you want to edit the fields groups that are reused in ACF then you must export those field groups as well and include this plugin in sites where you import them to.

If you want to export these into PHP then you can export the reused field groups as well, however, I don't know how that would work.

If you want to export the entire groups into PHP and include the resusable fields then look in the acf-json folder in this plugin. In this folder you will find the actual field groups that this plugin creates. If you delete the original field group from ACF and then import the file for that group from the json files it creates you could then use ACF to export it from there.

Having an export that includes the reusable fields defeats the purpose of having reusable fields.

If I've somehow missed what you were asking let me know.

**Comment by ReggaePanda** [comment]
Sorry, my english is not the best. But I'll try to explain it better.

I use this plugin local and export via the ACF-export function all field groups in a PHP file.

On my server I do import this PHP file. There I also enabled this plugin. However, I do not see the fields specified.

When I add the changes indicated above in this plugin, the fields are generated even after embed the PHP file.

**Comment by Hube2** [comment]
In order for this plugin to work and not cause performance issues on the site it loads field groups that it creates from a cache of JSON files that it saves locally in the acf-json folder inside of this plugin. This happens before ACF loads any fields groups or fields.

If there are no json files found in this folder then this plugin builds the fields after ACF is done loading fields. This happens on the ACF hook `acf/include_fields` with a priority of 999.  The `acf/include_fields` action is fired on the WP `init` hook with a priority of 5. I don't know of a reason why this plugin would not build field groups that are included in PHP other than that they are being created after the hook it uses to do the building has already been fired.

If you are using the WP `init` hook to build your field groups in PHP then set the priority to < 5 and see if that corrects the problem. Or you can try creating your fields on the `acf/include_fields` hook instead.
