### ISSUE TITLE
Typo in plugin name

### ISSUE THREAD

**Issue by joeserg** [Hube2/acf-reusable-field-group-field#3]
First off, this is a great plugin and one I can see our team using a great deal. Only a minor issue, but I've noticed a slight typo in the plugin name:

<img width="429" alt="screen shot 2015-11-10 at 15 32 12" src="https://cloud.githubusercontent.com/assets/1327888/11066477/481cfd0a-87c0-11e5-95ee-95a4abed5246.png">

Keep up the good work!

**Comment by Hube2** [comment]
Thanks for letting me know that, I've made the change.
