### ISSUE TITLE
Caching Discussion

### ISSUE THREAD

**Issue by johnstew** [Hube2/acf-reusable-field-group-field#30]
Alright so I'm using this plugin and it works great for what I need it to do. However, it is causing some issues as well from a caching perspective because it uses acf-json feature. 

So the problem I currently have is I have to create my new field groups locally then I export them to JSON and them import that JSON on my prod server. I then have to push my changes in my git repo locally up to my prod server. This is fine and all but sometimes when I make changes to the rules on where these field groups show up it doesn't actually update the acf-json folder. So what happens is I go through and import/export my JSON file from local to prod but the changes won't reflect on prod because the acf-json is not updated.

This might be a larger ACF issue in terms of it not recognizing rule changes as updates to the acf-json feature. 

With that being said, I really don't think a custom field group plugin should dictate whether or not I utilize acf json caching feature. If this caching was enclosed to just the plugin then I'd be fine with it but it seems that it is not and is causing issues. I propose just removing that feature all together and then leaving it up to the developer to setup acf-json caching in their theme directory rather than in a plugin. 

Anyways, looking to hear some others thoughts.

**Comment by Hube2** [comment]
The current version of this plugin should be clearing the acf-json files on updating a field group or importing. I'm not too sure about syncing, I can look into that.

For an explanation of why this plugin does what it does please see this discussion https://github.com/Hube2/acf-reusable-field-group-field/issues/22. It really comes down to the fact that without the json files this plugin is a serious suck on resources and causes caching issues for anyone using any type of a persistent cache.

I'd like to hear what others have to say as well. I would entertain the idea of creating a constant than can be defined in wp-config.php to turn of the json files.

Also in the light of the fact that Eliot is working on a feature built into ACF that does what this plugin does... Well, I won't abandon this for those that don't want to rebuild existing sites, but that feature is pretty much going to kill this add on except for those already using it on existing sites.

**Comment by Hube2** [comment]
I'm looking into trying to solve this, have a question.

When you upload the .json files to the production server do you then sysnc the files on the ACF admin page or does ACF automatically load your changed field groups without syncing.

1) I need to figure out a way to detect that the acf json files have changed

2) I need to add a way to disable the local caching of json files in this plugin

**Comment by Hube2** [comment]
I have added a configuration setting in the last release so that saving and loading from local JSON files can be disabled. See the readme
