### ISSUE TITLE
json things

### ISSUE THREAD

**Issue by rg-** [Hube2/acf-reusable-field-group-field#32]
Here playing with a lot of fields and lot of resuable mixed into others and so on. 
I´m using the acf-json/ folder in my theme to keep local and dev and production sync.
Should i also update the files under: /wp-content/plugins/acf-reusable-field-group-field-master/acf-json ?
I´m confused about that particual point :)

Thanks, great tool by the way.

Ah by the way, i´m testing a very complex theme with thousands of fields and reusable ones (previously created with acf 5.3.10), with ACF 5.4... till now no problem seems like it´s another logic (the clone addon) that will not create confilct with yours.

**Comment by Hube2** [comment]
There is an discussion about the json files this plugin creates in issue #30 and working out how to handle when and why this plugin is not detecting that the acf json file changes happen.

As far as as the last part, I'm not surprised if this plugin and the new clone field don't play nice together and I'm not sure I'll be able to fix that. I'll have to wait until all the bugs are worked out of the clone field before I'm able to figure out if this plugin can work with them. My suggestion for now would be that if you're using this plugin not to try using the clone field.

**Comment by rg-** [comment]
Yeah i readed that also, but want to be sure if i was working the right way to avoid conflicts or strange things.

Actualy i´ve updated right now some acf-json in my theme and notice that the ones in the reusable plugin folder also where updated using just the sync thing from admin. So, that part worked ok.

The other thing about acf 5.4 and clone addon, i didnt test it hard on front-end, but i did install both, your addon and acf5.4, y´ve created both reusalbe fileds and clone fields inside some testing groups, and since i´m using diferent names for fields, i don´t think something could not work, unless has something to do the way acf handle json files in this new version..... don´t know.

I´m using your addon because it´s a life saver really, you rocked it!!, and it seems that is no problem updating acf to 5.4 and use it, you are right on the point of trying not to use clone at same time, je, i´ll try to find some time to test this deeper and i´ll tell you.

Thanks for your super quick reply.

**Comment by Hube2** [comment]
The problem I'm having with updating the acf-json in a theme is when the field groups in the theme are not included in the acf field groups list or the sync feature is not used. If you update the field groups is the acf-json folder, even if you don't sync them or they are not included in the list of ACF field groups in the field groups list, ACF loads these updated field groups from the json files. I haven't been able to figure out how to detect this condition and force a refresh of the files that this plugin creates. I could just be missing something.
