### ISSUE TITLE
Does not work inside Flexible Content or Repeater field types

### ISSUE THREAD

**Issue by joeserg** [Hube2/acf-reusable-field-group-field#4]
I was hoping to reuse a field group within a Flexible Content field type. I've created the Flexible Content field like so:

<img width="764" alt="screen shot 2015-11-10 at 16 30 30" src="https://cloud.githubusercontent.com/assets/1327888/11068328/bbb528b6-87c8-11e5-8482-ed024cb97e50.png">

However, when editing a page, the fields from my Reusable Field Group are missing:

<img width="760" alt="screen shot 2015-11-10 at 16 31 51" src="https://cloud.githubusercontent.com/assets/1327888/11068349/cebe7200-87c8-11e5-94ac-f4452afdb177.png">

Is there anything special I need to do in order for it to work correctly? Or is it just a case that this isn't supported yet?

**Comment by Hube2** [comment]
Is this with the current version. I updated it to look for fields in repeaters and flex fields after recently. Just want to make sure you using the newest version. If you are I'll take a look at it.

**Comment by Hube2** [comment]
Quick test shows that it's working in repeaters but not in flex fields. Looking into it now.

**Comment by Hube2** [comment]
Can you please test the new version and let me know it that fixes the problem with flex fields.

One thing I have not tested is where a field group that you're reusing included flexible fields. I am not prefixing the layout key. Not sure it this will cause issues or not. I'd probably avoid reusing field groups that include flexible content fields, I'm not sure I'll be able to fix this if it's a problem.

**Comment by joeserg** [comment]
Thanks for coming back to me so quickly. I've just tested the latest version and unfortunately I'm still seeing the same issue. Here are my steps to reproduce it in Wordpress:

1. Create a field group called 'Text Field', which contains a Wysiwyg Editor field named 'Text'. The Location Rules are set to: 'Special', 'Nowhere'.

2. Create a field group called 'Flexible Content Fields', which contains a Flexible Content field named 'Flexible Content'. The Location Rules are set to: 'Post Type', 'is equal to', 'Page'.

3. Add a Layout option named 'Text Content' to the Flexible Content field, which contains a Reusable Field Group field named 'Content'. The Field Group is set to 'Text Field' and both 'Field Name Prefixing' and 'Field Key Prefixing' are set to 'Yes'.

4. Go to Pages and create a new page, or edit an existing page.

5. Click 'Add Row' under the 'Flexible Content' field heading and choose 'Text Content'. The field heading of 'Content' appears, but the Wysiwyg Editor field does not render.

I've tried different types of fields in place of the Wysiwyg editor but the result is still the same.

**Comment by Hube2** [comment]
Did you select the field group that you wanted to reuse when creating the field?
<img src="http://www.ssird5.com.php53-8.dfw1-2.websitetestlink.com/test/reusable1.png" />
I've been doing some more testing and can't reproduce it not working in repeaters of flex fields. Here is an image of it working for me, top level, repeater and a flex field.
<img src="http://www.ssird5.com.php53-8.dfw1-2.websitetestlink.com/test/reusable2.png" />

**Comment by joeserg** [comment]
I think we've got our wires crossed a bit. I can created a reusable Repeater or Flexible Content field group with no issues. The problem I'm experiencing happens when I add a reusable field group **inside** a Repeater, or Flexible Content field.

**Comment by Hube2** [comment]
Except that I'm not having any issue with adding them and when I go to the post that uses the field group with the reusable fields in it all of the fields work and I can enter information into them. That is what my second image shows.

I cannot recreate the problem that you say you are having.

So I'm going to need to know what else is different. Have you deactivated other plugins? Are you trying it with a default theme?

**Comment by kalle0045** [comment]
System:
- ACF Version: ACF PRO 5.3.2
- WP Version: WordPress 4.3.1
- WP Plugins:  ACF PRO 5.3.2 and acf-reusable-field-group-field
- Template: TwitterBootstrap3BlankTheme

Bug:
Does not work inside Flexible Content or Repeater field.

**Comment by Hube2** [comment]
@joeserg, I'm still not able to recreate this problem. Can you let me know what other plugins you're using on the site and what theme? Also, have you changed and ACF's settings? I'd like to make sure this is working but I can't debug a problem that I can't recreate.

Thanks,

**Comment by joeserg** [comment]
@Hube2, very sorry for not coming back to you sooner. I've set up a fresh install on our boilerplate theme and it works! I've mirrored the activated plugins from the problematic install and it still behaves as expected.

I'm currently trying to work out what else could differ between the two installations.

**Comment by joeserg** [comment]
In the working install, a field label has the following value:

`acf-field_565730f86b125-0-field_565731076b126_5657303d37035`

On the broken install, the field label has this value instead:

`acf-field_564f2b66235b2-acfcloneindex-field_565c4f4996376`

Do you know where the 'acfcloneindex' value might come from? I couldn't see a reference to it in your plugin code.

**Comment by joeserg** [comment]
OK, so I've worked out why it's not working. I had another field group set up, which was already using the same reusable field. Adding a reusable field group inside a repeater on the original field group worked absolutely fine. When I try to use the reusable field group in another field group I am experiencing the issue.

So to clarify, the issue is when a reusable field group field is used in more than one field group.

**Comment by Hube2** [comment]
Thanks for the troubleshooting. I will test this out and see if I can work out what's causing the issue. I have some ideas where it might be, maybe.

**Comment by Hube2** [comment]
I've done some more testing. I created a field groups. I reused that field group in multiple times in multiple field groups, in both repeaters and flexible content fields. I even tested using these field groups in multiple times in multiple groups including in repeaters and flexible content.

The only thing that I can think of is that you have something lingering around on the site that's not working from a point when this wasn't working properly. I would suggest moving the field groups that are not working to the trash and then permanently deleting them. If you have set up the local acf-json folder in the theme I would also make sure that these field groups are deleted from there as well.

I've also just noticed that the acf field groups that can be selected also include fields groups that are in the trash or have been deleted if the local json file exists for them, you may be selecting something that should not be, though I'm not sure about that. I will be looking into making it so that only active groups can be selected.

**Comment by Hube2** [comment]
Thanks to the help of another bug report I think I finally got this nailed down. https://github.com/Hube2/acf-reusable-field-group-field/issues/12

**Comment by kalle0045** [comment]
hi John Huebner,
first, I would like to say thanks for the awsome support!http://support.advancedcustomfields.com/forums/topic/flexible-content-feature-request/
I have try the new plugin in my owen project and for a big customer, it´s work finally!It is so easy to use and my customer love it!I hope also the feature will be a standard part of ACF PRO!
I have a question about my licence... It ́s possible to get a free upgrate to the developer License?I will not use it for commercial customers just for my owen projects.
Thanks! 
Lars Larsen (craftfire)kalle0045@hotmail.com

----------- 
Date: Fri, 18 Dec 2015 12:09:15 -0800
