### ISSUE TITLE
Conditional logic does not work within reused field groups

### ISSUE THREAD

**Issue by michaeland** [Hube2/acf-reusable-field-group-field#6]
I've been trying to make a 'link' field group that has:

```
Link text (text)
Internal/External (select, with 2 options)
External URL (url)
Page (Page link)
```

The `External URL` and `Page` have conditional logic to show them when the `Internal/External` field is selected with the correct option.

When this field group is reused through a reusable field group, the `External URL` field and `Page` field do not show at all.

Is this behaviour supported, or should I look to put the conditional logic outside of the field group?

**Comment by Hube2** [comment]
I thought that this was working, I'll do some testing.

**Comment by Hube2** [comment]
field keys not being replaced with new field keys in conditional logic values.

**Comment by Hube2** [comment]
The latest update should fix this issue. Can you download the updated version and let me know if it's working for you now?

Thanks,
~JH

**Comment by Hube2** [comment]
Thanks to the help of another bug report I think I finally got this nailed down. https://github.com/Hube2/acf-reusable-field-group-field/issues/12
